### ISSUE TITLE
 As a logged-in user,  I could inspect other registered users’ profiles by clicking their profile pictures.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#2]
### Acceptance Criteria:
- [ ] The profile page contains the following data belonging to the selected user: username, creation date and birth date.
- [ ] A user can view the profile of another registered user’s profile by clicking his or her profile picture, and then the user will be redirected to a profile page of the corresponding user.
- [ ] A user can modify his or her own profile.

### Development Tasks:
- [ ] sopra-fs23-group-26/client#15
- [ ] sopra-fs23-group-26/client#16
- [ ] sopra-fs23-group-26/client#17
- [x] sopra-fs23-group-26/server#50
- [x] sopra-fs23-group-26/server#51
- [x] sopra-fs23-group-26/server#52

**Comment by Jess688688** [comment]
a57e2b018736c39efd6687b4b212136c0cfc982f
