### ISSUE TITLE
As a logged-in user, I could add other users as friends and join a game together with my friends.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#4]
### Acceptance Criteria:
- [ ] Users can send a friend request to any user as long as the username is known.
- [ ] Users can decide to accept or decline other users' friend requests.
- [ ] Users can send invitations to their friends to join the same game as teammates or as opponents.

### Development Tasks:
- [ ] sopra-fs23-group-26/client#18
- [ ] sopra-fs23-group-26/client#19
- [ ] sopra-fs23-group-26/client#20
- [ ] sopra-fs23-group-26/client#21
- [ ] sopra-fs23-group-26/client#22
- [ ] sopra-fs23-group-26/client#23
- [ ] sopra-fs23-group-26/server#59
- [ ] sopra-fs23-group-26/server#60
- [ ] sopra-fs23-group-26/server#61
- [ ] sopra-fs23-group-26/server#62

**Comment by Jess688688** [comment]
a57e2b018736c39efd6687b4b212136c0cfc982f
