### ISSUE TITLE
 As a logged-in user, I could play the Sudoku Game alone.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#40]
###Acceptance Criteria:
- [x] The game only requires 1 player to participate in.
- [x] Each player is required to fill a 9 × 9 grid with digits so that each column, each row, and each of the nine 3 × 3 subgrids that compose the grid contain all of the digits from 1 to 9.
- [x] The player who successfully meets requirements will win 2 points.

### Development Tasks:
- [x] sopra-fs23-group-26/client#50
- [x] sopra-fs23-group-26/client#51
- [x] sopra-fs23-group-26/server#130
- [x] sopra-fs23-group-26/server#111
- [x] sopra-fs23-group-26/server#112

**Comment by Jess688688** [comment]
e36173e37f5426a2790e51b3131b3472af2beaf4
