### ISSUE TITLE
 As a logged-in user, I could create a room where I can invite other users to play games together.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#5]
### Acceptance Criteria:
- [x] Users create a private virtual game room to join a game together.
- [x] Users can invite other users to join the room.

### Development Tasks:
- [x] sopra-fs23-group-26/client#24
- [x] sopra-fs23-group-26/client#25
- [x] sopra-fs23-group-26/client#26
- [x] sopra-fs23-group-26/client#27
- [x] sopra-fs23-group-26/server#68
- [x] sopra-fs23-group-26/server#67
- [x] sopra-fs23-group-26/server#69
- [x] sopra-fs23-group-26/server#70
