### ISSUE TITLE
As a user, I want to be able to browse and select games that I can play on the platform

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#6]
### Acceptance Criteria:
- [ ] Users can browse the list of games available on the platform.
- [ ] Users can filter the games based on different criteria such as genre, popularity, etc.
- [ ] Users can select a game to play.
### Development Tasks:

- [ ] sopra-fs23-group-26/client#28
- [x] sopra-fs23-group-26/client#29
- [ ] sopra-fs23-group-26/server#73
