### ISSUE TITLE
As a logged-in user, I could invite my friends or randomly match other users to play Who is undercover.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#8]
### Acceptance Criteria:
- [ ] The game requires at least three players, with no maximum limit.
- [ ] Each player randomly gets the same word, only one player gets another word.
- [ ] Each player in turn describes the word they get, and when a round ends, everyone has to vote for who they think is undercover.
- [ ] The player who gets the most vote are out, the game continue until there is only two players or undercover is spotted
- [ ] If undercover is still in the game at the end, then undercover wins and gets two points, otherwise everyone except undercover gets one point.

### Development Tasks:
- [ ] sopra-fs23-group-26/client#30
- [ ] sopra-fs23-group-26/client#31
- [x] sopra-fs23-group-26/client#32
- [x] sopra-fs23-group-26/client#33
- [ ] sopra-fs23-group-26/client#34
- [x] sopra-fs23-group-26/client#35
- [ ] sopra-fs23-group-26/server#80
- [x] sopra-fs23-group-26/server#81
- [ ] sopra-fs23-group-26/server#82
- [x] sopra-fs23-group-26/server#83
- [x] sopra-fs23-group-26/server#84
- [x] sopra-fs23-group-26/server#85
- [x] sopra-fs23-group-26/server#86

**Comment by Jess688688** [comment]
28e581801b50306b797e112d535bb4f8c6d82bb3
