### ISSUE TITLE
As a logged-in user, I could invite my friends or randomly match other users to play Draw and Guess.

### ISSUE THREAD

**Issue by Roger672** [sopra-fs23-group-26/server#9]
### Acceptance Criteria:
- [ ] The game requires at least two players, with no maximum limit.
- [ ] Each player takes turns being the "drawer" for a round, while the other players are the "guessers".
- [ ] The drawer is given a random word or phrase to draw on the screen.
- [ ] The other players have one minute to guess what the drawer is drawing.
- [ ] The first player to correctly guess the word or phrase earns a point.
- [ ] If no one guesses correctly within the time limit, the drawer does not earn any points, and a new drawer is chosen for the next round.
- [ ] The game continues for three rounds and the points will be counted as credits for the users.

### Development Tasks:
- [ ] sopra-fs23-group-26/client#36
- [ ] sopra-fs23-group-26/client#37
- [ ] sopra-fs23-group-26/client#38
- [ ] sopra-fs23-group-26/client#39
- [ ] sopra-fs23-group-26/client#40
- [ ] sopra-fs23-group-26/client#41
- [ ] sopra-fs23-group-26/client#42
- [ ] sopra-fs23-group-26/server#94
- [ ] sopra-fs23-group-26/server#95
- [ ] sopra-fs23-group-26/server#96
- [ ] sopra-fs23-group-26/server#97
- [ ] sopra-fs23-group-26/server#98
- [ ] sopra-fs23-group-26/server#99
- [ ] sopra-fs23-group-26/server#100
- [ ] sopra-fs23-group-26/server#101
